name: Build and Test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

env:
  DATABASE: ${{ secrets.DATABASE }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.1'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: echo "The port is $PORT for the $DB_NAME"
